# Generated by Django 6.0.5 on 2026-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='categoria',
            field=models.CharField(choices=[('Lenguajes', 'Lenguajes de Programación'), ('Frameworks', 'Frameworks y Librerías'), ('Plataformas', 'Plataformas o Software'), ('Herramientas', 'Herramientas (Excel, Git, etc.)')], default='Lenguajes', max_length=50),
        ),
    ]
